version: "3.8"
name: keycloak
services:
  keycloak-server:
    image: jboss/keycloak
    hostname: keycloak-server
    container_name: keycloak-server
    depends_on:
      - sql-db
    environment:
      DB_VENDOR: mssql
      DB_ADDR: sql-db
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: Test123*
      DB_DATABASE: Keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Test123*
    ports:
      - 9090:8080
    networks:
      - keycloak-net
  sql-db:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    hostname: sql-db
    container_name: sql-db
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_PID: Express
      SA_PASSWORD: Test123*
      ACCEPT_EULA: Y
    volumes:
      - keycloak-mssql-server-data:/var/opt/mssql/data
    networks:
      - keycloak-net
volumes:
  keycloak-mssql-server-data:
networks:
  keycloak-net: