version: "3.8"
name: keycloak
services:
  keycloak-server:
    image: jboss/keycloak
    hostname: keycloak-server
    container_name: keycloak-server
    depends_on:
      - ms-sql
      - mssqlscripts
    environment:
      DB_VENDOR: mssql
      DB_ADDR: ms-sql
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: Test123*
      DB_DATABASE: Keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Test123*
    ports:
      - 9090:8080
    networks:
      - keycloak-net
  ms-sql:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    hostname: ms-sql
    container_name: ms-sql
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_PID: Express
      SA_PASSWORD: Test123*
      ACCEPT_EULA: Y
    volumes:
      - keycloak-mssql-server-data:/var/opt/mssql/data
    networks:
      - keycloak-net
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - ms-sql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S ms-sql -U sa -P "Test123*" -Q "CREATE DATABASE Keycloak"; do sleep 5; done'
    networks:
      - keycloak-net
volumes:
  keycloak-mssql-server-data:
networks:
  keycloak-net:
# NOTE: Run the following command to up all service and when the database 'Keycloak' was created 
# delete the service 'mssqlscripts' because isn't necesary to keep:
# docker-compose up -d && sleep 20 && docker-compose rm mssqlscripts -f