version: "3.8"
name: mysql
services:
  mysql-db:
    image: mysql:latest
    hostname: mysql-server
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: Test123*
      MYSQL_DATABASE: TestDB
      MYSQL_USER: TestUser
      MYSQL_PASSWORD: TestUserPassword123*
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mysql_net
volumes:
  mysql-data:
networks:
  mysql_net:
