version: "3.8"
name: mysql
services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Test123*
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql_net
volumes:
  mysql-data:
networks:
  mysql_net:
