version: "3.8"
name: mssql-server
services:
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      MSSQL_PID: Express
      SA_PASSWORD: Test123*
      ACCEPT_EULA: Y
    volumes:
      - mssql-server-data:/var/opt/mssql/data
    networks:
      - mssql-server-net
volumes:
  mssql-server-data:
networks:
  mssql-server-net:
