version: "3.8"
name: postgres-server
services:
  postgres:
    image: postgres:latest
    hostname: postgres-server
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - postgres-net
volumes:
  postgres-data:
networks:
  postgres-net:
