version: "3.8"
name: jenkins
services:
  jenkins-server:
    container_name: jenkins-server
    image: jenkinsci/jenkins
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_net
volumes:
  jenkins_home:
networks:
  jenkins_net:
