version: "3.8"
name: sonarqube
services:
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - postgres-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-db:5432/sonar
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: Test123*
    volumes:
      - sonarqube:/opt/sonarqube
    ports:
      - "9000:9000"
    networks:
      - "sonarqube-net"
  postgres-db:
    image: postgres:13
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Test123*
      POSTGRES_DB: sonar
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - "sonarqube-net"
volumes:
  sonarqube:
  postgres:
networks:
  sonarqube-net:
# Note: Default values for 'User: admin' and 'Password: admin'