version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.8.9-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=Test123*"
    networks:
      - "my-net"
networks:
  my-net: