apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-dp
  namespace: mariadb-ns
  labels:
    app: mariadb
    type: database
spec:
  selector:
      matchLabels:
        app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.7
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-mariadb
                  key: APP_DB_ROOT_PASS
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef: 
                  name: cm-mariadb
                  key: APP_DB_SCHEMA
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-mariadb
                  key: APP_DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: cm-mariadb
                  key: APP_DB_PASS
          volumeMounts:
          - name: mariadb-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: mariadb-ns
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 30306
  type: LoadBalancer
#apiVersion: v1
#kind: Service
#metadata:
#  name: mariadb-svc
#  namespace: mariadb-ns
#spec:
#  selector:
#    app: mariadb
#  ports:
#    - protocol: TCP
#      port: 3306
#      targetPort: 3306
#  clusterIP: None      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: mariadb-ns
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
