version: "3.8"
name: rabbitmq-server
services:
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq-server
    container_name: rabbitmq-server
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Test123*
    networks:
      - rabbitmq-net
networks:
  rabbitmq-net:
