version: "3.8"
name: gitlab
services:
  gitlab:
    container_name: gitlab
    hostname: gitlab.example.com
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - 443:443
      - 80:80
      - 22:22
    restart: always
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab_net
volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
networks:
  gitlab_net:
