version: "3.7"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      - "MSSQL_PID=Express"
      - "SA_PASSWORD=MyPass@word"
      - "ACCEPT_EULA=Y"
    networks:
      - "my-net"
networks:
  my-net: